name: 
     type: string
     required: True

location:
        type: string
        required: False

modbusDevID:
        type: integer
        min: 2
        max: 247
        required: True

deviceMetaID:
        type: integer
        min: 0
        required: True

devIDRegister:
        required: True
        type: dict
        schema:
                addr: 
                        type: integer
                        min: 0
                        max: 10000
                regType: 
                        type: string
                        allowed:
                                - holding       # output holding reg
                                - input         # analog input regs

state:
        required: True
        type: string
        allowed:
                - active
                - inactive
                - dormant

priority:
        required: True
        type: integer
        min: 0
        max: 2


devModbusEndianness:
        required: True
        type: dict
        schema:
                word:
                        required: True
                        type: string
                        allowed:
                                - big
                                - little
                byte:
                        required: True
                        type: string
                        allowed:
                                - big
                                - little




WriteMultipleRegistersFunctionSupport:
        type: boolean
        required: True
        #default: False




readRegs:
        type: list
        schema: 
                type: dict
                schema:
                        regType:
                                required: True
                                type: string
                                allowed: 
                                        - holding
                                        - input
                        addr:
                                required: True
                                type: integer
                                max: 65535
                                min: 0
                        nRegs:
                                required: True
                                type: integer
                                max: 100
                                min: 1
                        unit:
                                required: False
                                type: string
                        
                        unpackFormat:
                                required: True
                                type: string
                                allowed: 
                                        #('string', decoder.decode_string(8)),
                                        #('bits', decoder.decode_bits()),
                                        #('8int', decoder.decode_8bit_int()),
                                        #('8uint', decoder.decode_8bit_uint()),
                                        #('16int', decoder.decode_16bit_int()),
                                        #('16uint', decoder.decode_16bit_uint()),
                                        #('32int', decoder.decode_32bit_int()),
                                        #('32uint', decoder.decode_32bit_uint()),
                                        #('32float', decoder.decode_32bit_float()),
                                        #('32float2', decoder.decode_32bit_float()),
                                        #('64int', decoder.decode_64bit_int()),
                                        #('64uint', decoder.decode_64bit_uint()),
                                        #('ignore', decoder.skip_bytes(8)),
                                        #('64float', decoder.decode_64bit_float()),
                                        #('64float2', decoder.decode_64bit_float()),
                                        
                                        - int8
                                        - int16
                                        - int32
                                        - int64

                                        - uint8
                                        - uint16
                                        - uint32
                                        - uint64
                                        
                                        - float32
                                        - float64

                                        - string
                        

                                        
                        rate:
                                required: True
                                type: float
                                max: 500
                                min: 0.0014
                        scaling:
                                required: False
                                type: float
                                min: 0

                        mqttSubTopic:
                                required: True
                                type: string
                                 

writeRegs:
        type: list
        schema:
                type: dict
                schema:
                        regType:
                                required: True
                                type: string
                                allowed: 
                                        - holding
                                        #- input
                        addr:
                                required: True
                                type: integer
                                max: 65535
                                min: 0

                        packFormat:
                                required: True
                                type: string
                                allowed:
                                        #('string', decoder.decode_string(8)),
                                        #('bits', decoder.decode_bits()),
                                        #('8int', decoder.decode_8bit_int()),
                                        #('8uint', decoder.decode_8bit_uint()),
                                        #('16int', decoder.decode_16bit_int()),
                                        #('16uint', decoder.decode_16bit_uint()),
                                        #('32int', decoder.decode_32bit_int()),
                                        #('32uint', decoder.decode_32bit_uint()),
                                        #('32float', decoder.decode_32bit_float()),
                                        #('32float2', decoder.decode_32bit_float()),
                                        #('64int', decoder.decode_64bit_int()),
                                        #('64uint', decoder.decode_64bit_uint()),
                                        #('ignore', decoder.skip_bytes(8)),
                                        #('64float', decoder.decode_64bit_float()),
                                        #('64float2', decoder.decode_64bit_float()),
                                        
                                        - int8
                                        - int16
                                        - int32
                                        - int64

                                        - uint8
                                        - uint16
                                        - uint32
                                        - uint64
                                        
                                        - float32
                                        - float64

                                        - string
                        
                        scaling:
                                required: False
                                type: float
                                min: 0

                        mqttSubTopic:
                                required: True
                                type: string
                        rate:
                                # Maybe writing is not scheduled but is done async as message arrives on MQTT topic
                                # In such case rate is set to zero (0)
                                # Currently only async is allowed, so must be enforced to zero (0)
                                required: True 
                                type: float
                                max: 0
                                min: 0





